In [1]:
using Test

In [86]:
function ispangram(input)
    letters = Dict(c=>false for c in 'a':'z')
    for c in lowercase(input)
        if isletter(c)
            letters[ c ] = true
        end
    end
    all(values(letters))
end;

In [87]:
@testset "ispangram tests" begin
    @test ispangram("The quick brown fox jumps over the lazy dog.") == true;
    @test ispangram("The quick brown fox jumps over the lazy dog") == true;
    @test ispangram("The quick brown fox jumps over the lazy do") == false;
end;

Test Summary:   | Pass  Total
ispangram tests |    3      3


In [85]:
function ispangram1(input)
    filter(isletter,lowercase(input)) |> Set |> length == 26
end;

In [83]:
@testset "ispangram1 tests" begin
    @test ispangram1("The quick brown fox jumps over the lazy dog.") == true;
    @test ispangram1("The quick brown fox jumps over the lazy dog") == true;
    @test ispangram1("The quick brown fox jumps over the lazy do") == false;
    end;

Test Summary:    | Pass  Total
ispangram1 tests |    3      3


In [88]:
function ispangram2(input)
    'a':'z' ⊆ lowercase(input)
end;

In [84]:
@testset "ispangram2 tests" begin
    @test ispangram2("The quick brown fox jumps over the lazy dog.") == true;
    @test ispangram2("The quick brown fox jumps over the lazy dog") == true;
    @test ispangram2("The quick brown fox jumps over the lazy do") == false;
end;

Test Summary:    | Pass  Total
ispangram2 tests |    3      3


In [79]:
collect("The quick brown fox jumps over the lazy do");

In [150]:
function count_nucleotides(strand::AbstractString)
    count = Dict(n=>0 for n in "ACGT")
    for n in strand
        if n ∈ keys(count)   #haskey(count,n)
            count[n] += 1
        else
            throw(DomainError)
        end
    end
    return count
end;

In [151]:
@test count_nucleotides("") == Dict('A' => 0, 'C' => 0, 'G' => 0, 'T' => 0)

Test Passed
  Expression: count_nucleotides("") == Dict('A' => 0, 'C' => 0, 'G' => 0, 'T' => 0)
   Evaluated: Dict('A' => 0, 'G' => 0, 'T' => 0, 'C' => 0) == Dict('A' => 0, 'G' => 0, 'T' => 0, 'C' => 0)

In [152]:
circshift('a':'z',13);

In [157]:
function rotate(n::Integer,input)
    result = collect(input)
    for (i,c) in enumerate(result)
        if isletter(c)
            orig = isuppercase(c) ? 'A' : 'a'
            result[i] = isletter(c) ? orig + (c - orig + n) % 26 : c
        end
    end
    return typeof(input)==AbstractString ? join(result) : result[1]
end;

In [160]:
@testset "rotate tests" begin
    @test rotate(1,'a') == 'b'
    @test rotate(1,"a") == "b"
    @test rotate(13,"abcdefghijklmnopqrstuvwxyz") == "nopqrstuvwxyzabcdefghijklm"    
end;

Test Summary: | Pass  Total
rotate tests  |    3      3


In [147]:
macro ROT13_str(p)
    rotate(13,p)
end

@ROT13_str (macro with 1 method)

In [148]:
ROT13"dupa blada"

"qhcn oynqn"

In [ ]:
function detect_anagrams(subject::AbstractString, candidates::AbstractArray)
    hash = sort ∘ collect ∘ lowercase
    filter(candidates) do cand
        lowercase(subject) ≠ lowercase(cand) && hash(subject) == hash(cand)
  end
end

In [ ]:
function detect_anagrams(subject, candidates)
    sl = lowercase(subject)
    subject = lowercase(subject) |> collect |> sort
    isAnagram(x) = subject == lowercase(x) |> collect |> sort
    result = []
    for a in filter(isAnagram,candidates)
        al = lowercase(a)
        if al ∉ result && al != sl
            push!(result,a)
        end
    end
    result
end

In [ ]:
function acronym(phrase) 
    join([uppercase(w[1]) for w in split(phrase,[' ', '-','_']; keepempty=false)])
end

In [3]:
isword(x) = filter(x->isletter(x)|isdigit(x),x)

isword (generic function with 1 method)

In [7]:
isword(" .\n,\t!^&*()~@#\$%{}[]:;'/<>")

""

In [13]:
t = "to jest jest test"
t |> uppercase

"TO JEST JEST TEST"

In [18]:
function count_words(sentence)
    isword(x) = filter(x->isletter(x)|isdigit(x),x)
    count = Dict()
    for m in eachmatch(r"[\w\d]+",sentence)
        word = m.match
        if length(isword(word)) != 0
            count[word] = get!(count, word, 0) + 1
        end
    end
    return count
end;

In [19]:
count_words("to jest jest test to test")

Dict{Any, Any} with 3 entries:
  "test" => 2
  "to"   => 2
  "jest" => 2

In [78]:
for m in eachmatch(r"\w+('\w)?","Joe can't tell between 'large' and large.")
    println( m.match )
end

Joe
can't
tell
between
large
and
large


In [79]:
function countmap(X)
    count = Dict{eltype(X),Int}()
    for x in X
        count[x] = get(count,x,0) + 1
    end
    count
end;

In [76]:
"Joe can't tell between 'large' and large." |> lowercase |> s->[m.match for m in eachmatch(r"\w+('\w)?",s)] |> countmap

Dict{SubString{String}, Int64} with 6 entries:
  "tell"    => 1
  "can't"   => 1
  "large"   => 2
  "joe"     => 1
  "between" => 1
  "and"     => 1

In [81]:
d = Dict( 1=> ['a','b','c'] )

Dict{Int64, Vector{Char}} with 1 entry:
  1 => ['a', 'b', 'c']

In [82]:
Dict( x => 1 for x in "abc")

Dict{Char, Int64} with 3 entries:
  'a' => 1
  'c' => 1
  'b' => 1

In [ ]:
transform(input::AbstractDict) = Dict(lowercase(v) => key for (key, value) in input for v in value)

In [ ]:
function transform(input::AbstractDict)
    score = Dict()
    for (k,V) in input
        merge!(score, Dict([lowercase(x)=>k for x in V]))
    end
    score
end

In [87]:
function transform(input::AbstractDict)
    merge((Dict(lowercase(z) => x for z in y) for (x, y) in input)...)
end

transform (generic function with 1 method)

In [89]:
function transform(input::AbstractDict)
    for (x, y) in input
        subd = Dict(lowercase(z) => x for z in y)
        println( subd )
    end
end

transform (generic function with 1 method)

In [90]:
input = Dict(1=>['A', 'E'], 2=>['D', 'G'])
transform(input)

Dict('g' => 2, 'd' => 2)
Dict('a' => 1, 'e' => 1)


In [92]:
input = [ Dict(1=>['A', 'E']), Dict(2=>['D', 'G'])]
merge(input...)

Dict{Int64, Vector{Char}} with 2 entries:
  2 => ['D', 'G']
  1 => ['A', 'E']

In [97]:
function spiral_matrix(n)
    totelem = n^2
    zeros(Int,n,n)
end

spiral_matrix (generic function with 1 method)

In [98]:
spiral_matrix(3)

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0

In [105]:
reshape([1 2 3 8 9 4 7 6 5],(3,3))'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  2  3
 8  9  4
 7  6  5

In [106]:
reshape([1],1,1)

1×1 Matrix{Int64}:
 1

In [112]:
typeof([1])

Vector{Int64} (alias for Array{Int64, 1})

In [1]:
1 .<< [0 1 2 3 4 5 6 7]

1×8 Matrix{Int64}:
 1  2  4  8  16  32  64  128

In [6]:
const allergies = Dict(1=>"eggs", 2=>"peanuts", 4=>"shellfish", 8=>"strawberries", 16=>"tomatoes", 32=>"chocolate", 64=>"pollen", 128=>"cats");

LoadError: cannot declare allergies constant; it already has a value

In [7]:
rev = Dict(v=>k for (k,v) in allergies)

Dict{String, Int64} with 8 entries:
  "pollen"       => 64
  "peanuts"      => 2
  "tomatoes"     => 16
  "eggs"         => 1
  "chocolate"    => 32
  "shellfish"    => 4
  "cats"         => 128
  "strawberries" => 8

In [33]:
function isisogram(s)
    cleaned = filter(isletter,s)
    length(cleaned) == cleaned |> lowercase |> Set |> length
end

isisogram (generic function with 1 method)

In [26]:
function isisogram2(s)
    cleaned = filter(isletter,lowercase(s))
    collect(cleaned) == unique(cleaned)
end

isisogram2 (generic function with 1 method)

In [27]:
isisogram2("Hjelmqvist-Gryb-Zock-Pfund-Wax")

true

In [28]:
@test !isisogram2("eleven")

Test Passed
  Expression: !(isisogram2("eleven"))

In [34]:
@test isisogram("subdermatoglyphic")

Test Passed
  Expression: isisogram("subdermatoglyphic")

In [32]:
 cleaned = filter(isletter,lowercase("subdermatoglyphic")), unique(cleaned), collect(cleaned)

("subdermatoglyphic", Any["subdermatoglyphic", ['s', 'u', 'b', 'd', 'e', 'r', 'm', 'a', 't', 'o', 'g', 'l', 'y', 'p', 'h', 'i', 'c']], Any["subdermatoglyphic", ['s', 'u', 'b', 'd', 'e', 'r', 'm', 'a', 't', 'o', 'g', 'l', 'y', 'p', 'h', 'i', 'c']])

In [52]:
factorize(n) = [i for i in 1:(n-1) if n%i==0]

factorize (generic function with 1 method)

In [56]:
6 |> factorize |> sum == 6

true

In [57]:
function is_equilateral(sides)
    all( sides .== sides[1])
end

is_equilateral (generic function with 1 method)

In [69]:
all(map(isuppercase,collect("DUPA BLADA")))

false

In [78]:
stimulus = "Dupa Blada";
cleaned = filter(isletter,stimulus)
map(isuppercase, cleaned)
#is_yell = all(filter(isuppercase, cleaned))

LoadError: ArgumentError: map(f, s::AbstractString) requires f to return AbstractChar; try map(f, collect(s)) or a comprehension instead

In [13]:
function bob(stimulus)
    is_question = length(stimulus) != 0 && stimulus[end] == '?'
    #cleaned = filter(x->isletter(x)||isdigit(x),stimulus) |> collect
    cleaned = filter(isletter,stimulus) |> collect
    length(cleaned) == 0 && !is_question && return "Fine. Be that way!"
    is_yell = all(map(isuppercase, cleaned)) && length(cleaned) != 0
    if is_question
        is_yell ?  "Calm down, I know what I'm doing!" : "Sure."
    elseif is_yell
        "Whoa, chill out!"
    else
        "Whatever."
    end
end

bob (generic function with 1 method)

In [14]:
miscs = (
        "Tom-ay-to, tom-aaaah-to.",
        "Let's go make out behind the gym!",
        "It's OK if you don't want to work for the NSA.",
        "Es ist okay, wenn du nicht für den BND arbeiten möchtest.",
        "1, 2, 3",
        "Ending with ? means a question.",
        "\nDoes this cryogenic chamber make me look fat?\nno",
        "         hmmmmmmm...",
        "This is a statement ending with whitespace      ",
        "Oida."
);
yells = (
        "WATCH OUT!",
        "FCECDFCAAB",
        "FCÄEÜCÖDFCẞAB",
        "1, 2, 3 GO!",
        "ZOMG THE %^*@#\$(*^ ZOMBIES ARE COMING!!11!!1!",
        "I HATE YOU",
        "I HATE THE DENTIST",
        "OIDA!"
);

In [15]:
@testset "misc" begin
    @testset "$misc" for misc in miscs
        @test bob(misc) == "Whatever."
    end
end

1, 2, 3: Test Failed at In[15]:3
  Expression: bob(misc) == "Whatever."
   Evaluated: "Fine. Be that way!" == "Whatever."
Stacktrace:
 [1] macro expansion
   @ C:\Users\johny\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Test\src\Test.jl:445 [inlined]
 [2] macro expansion
   @ .\In[15]:3 [inlined]
 [3] macro expansion
   @ C:\Users\johny\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Test\src\Test.jl:1359 [inlined]
 [4] macro expansion
   @ .\In[15]:2 [inlined]
 [5] macro expansion
   @ C:\Users\johny\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Test\src\Test.jl:1283 [inlined]
 [6] top-level scope
   @ .\In[15]:2
Test Summary:                                               | Pass  Fail  Total
misc                                                        |    9     1     10
  Tom-ay-to, tom-aaaah-to.                                  |    1            1
  Let's go make out behind the gym!                         |    1            1
  It's OK if you don

LoadError: Some tests did not pass: 9 passed, 1 failed, 0 errored, 0 broken.

In [12]:
@testset "yell" begin
    @testset "$yell" for yell in yells
        @test bob(yell) == "Whoa, chill out!"
    end
end

1, 2, 3 GO!: Test Failed at In[12]:3
  Expression: bob(yell) == "Whoa, chill out!"
   Evaluated: "Whatever." == "Whoa, chill out!"
Stacktrace:
 [1] macro expansion
   @ C:\Users\johny\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Test\src\Test.jl:445 [inlined]
 [2] macro expansion
   @ .\In[12]:3 [inlined]
 [3] macro expansion
   @ C:\Users\johny\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Test\src\Test.jl:1359 [inlined]
 [4] macro expansion
   @ .\In[12]:2 [inlined]
 [5] macro expansion
   @ C:\Users\johny\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Test\src\Test.jl:1283 [inlined]
 [6] top-level scope
   @ .\In[12]:2
ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!: Test Failed at In[12]:3
  Expression: bob(yell) == "Whoa, chill out!"
   Evaluated: "Whatever." == "Whoa, chill out!"
Stacktrace:
 [1] macro expansion
   @ C:\Users\johny\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Test\src\Test.jl:445 [inlined]
 [2] macro expansion
  

LoadError: Some tests did not pass: 6 passed, 2 failed, 0 errored, 0 broken.